### ISSUE TITLE
Set up domain on RPI server

### ISSUE THREAD

**Issue by CorneliusHsiao** [ZiniuYu/GoogleCardboardVR-AR#10]
Our current database is on AWS so there is monthly fee. We need to move to RPI server. Please negotiate this issue with CS department, and Communication department.

**Comment by shanalily** [comment]
Just realized I wrote an essentially duplicate issue, however we do have a domain now so I'm going to close this issue. We have been working w/ Professor Turner and Steven Lindsey. Media files can be found at https://cardboard.cs.rpi.edu/.
