### ISSUE TITLE
Find more precise GPS data

### ISSUE THREAD

**Issue by CorneliusHsiao** [ZiniuYu/GoogleCardboardVR-AR#13]
At present, the GPS data of each image in JSON file of Milestone 2 is obtained from Google Maps by selecting approximate points. This will generate errors when amount of images becomes more and more and when wrong point is pinned. 

Here are two suggestions that I will also put into documentation of project: 
1) Use Google Maps on your phone at every point you take pictures and record the data.
2) Use Exif data of photos.

**Comment by shanalily** [comment]
Ziyang and I have found that the GPS data on his phone seems pretty accurate.
