### ISSUE TITLE
Incorporate aframe in CampusDirections program to show the paths found

### ISSUE THREAD

**Issue by shanalily** [ZiniuYu/GoogleCardboardVR-AR#8]
When we find a path, the image of the starting location needs to show up and the rest of the images should be queued so we can click through images to get to destination. This requires incorporating aframe with the project. I'm not sure if this will happen directly on page Yanjun and I have been working on or if user will be brought to a second page.

**Comment by CorneliusHsiao** [comment]
@HarryXu12138 is doing the compatibility part with aframe. The general idea is to insert direction arrow or other buttons manually, and this requires tons of repeated work. Harry may teach us how to do it and we can share the workload.

**Comment by shanalily** [comment]
Okay. I was probably going to try this too so maybe we can compare implementations.
